/*
 * 問題バンク（横浜市立南高校附属中 適性検査むけ 1問1答）
 *
 * 南附属中の適性検査でよく問われる力を、小6が取り組みやすい1問1答に
 * かみくだいたオリジナル練習問題です（本番の過去問そのものではありません）。
 *
 * 分野(category) … 得意・不得意を見るための8分野
 *   kotoba  : ことば・漢字（適性Ⅰ 言語）
 *   dokkai  : 文章・資料の読み取り（適性Ⅰ）
 *   kazu    : 数の性質・規則性（適性Ⅱ 算数）
 *   zukei   : 図形（適性Ⅱ 算数）
 *   wariai  : 割合・速さ・場合の数（適性Ⅱ 算数）
 *   rika    : 理科（適性Ⅱ）
 *   shakai  : 社会（資料分析・一般常識）
 *   shikou  : 思考力・パズル（適性Ⅰ 前半のパズル系）
 *
 * type     … "input"（記述で答える） / "choice"（選択肢から選ぶ）
 * level    … 1=やさしい 2=ふつう 3=チャレンジ
 * answer   … 正解（input は文字列、choice は正解の選択肢の文字列）
 * accept   … input のとき、正解とみなす別表記（任意）
 */

const CATEGORIES = {
  kotoba: { name: "ことば・漢字", emoji: "📝", color: "#ef6c9b" },
  dokkai: { name: "読み取り", emoji: "📖", color: "#8e7cff" },
  kazu:   { name: "数と規則", emoji: "🔢", color: "#2d9cdb" },
  zukei:  { name: "図形",     emoji: "📐", color: "#27ae60" },
  wariai: { name: "割合・速さ", emoji: "⚖️", color: "#f2994a" },
  rika:   { name: "理科",     emoji: "🔬", color: "#16a085" },
  shakai: { name: "社会",     emoji: "🗾", color: "#c0392b" },
  shikou: { name: "思考力",   emoji: "🧩", color: "#9b59b6" },
};

const QUESTIONS = [
  /* ===== ことば・漢字 ===== */
  { id: "kotoba01", category: "kotoba", level: 1, type: "input",
    q: "「快い」の読みをひらがなで答えましょう。", answer: "こころよい", accept: ["こころよい"],
    hint: "気持ちがよい、という意味の言葉です。", exp: "「快い（こころよい）」＝気持ちがよい・さわやか。" },
  { id: "kotoba02", category: "kotoba", level: 1, type: "input",
    q: "「需要」の反対の意味の言葉（対義語）を漢字2字で答えましょう。", answer: "供給", accept: ["供給"],
    hint: "ものを「もとめる」⇔ものを「あたえる」。", exp: "需要⇔供給。経済の資料問題でよく出ます。" },
  { id: "kotoba03", category: "kotoba", level: 1, type: "input",
    q: "ことわざ「□の上にも三年」。□に入る漢字1字は？", answer: "石", accept: ["石"],
    hint: "つめたくても、すわり続ければあたたまる。", exp: "「石の上にも三年」＝がまん強く続ければ成功する。" },
  { id: "kotoba04", category: "kotoba", level: 2, type: "input",
    q: "四字熟語「一□一会」。□に入る漢字1字は？", answer: "期", accept: ["期"],
    hint: "一生に一度の出会い、という意味。", exp: "「一期一会（いちごいちえ）」＝一生に一度のめぐりあい。" },
  { id: "kotoba05", category: "kotoba", level: 2, type: "choice",
    q: "「重要」とほぼ同じ意味の言葉（類義語）はどれ？",
    choices: ["大切", "便利", "正直", "新鮮"], answer: "大切",
    hint: "「大事」とも言いかえられます。", exp: "重要≒大切・大事。" },
  { id: "kotoba06", category: "kotoba", level: 1, type: "input",
    q: "慣用句「□を貸す」は「手伝う」という意味。□に入る体の部分は？", answer: "手", accept: ["手"],
    hint: "作業を手伝うときに使う部分。", exp: "「手を貸す」＝力をかして手伝う。" },
  { id: "kotoba07", category: "kotoba", level: 2, type: "input",
    q: "「過去・現在・□□」。これからのことを表す□□の言葉を漢字2字で。", answer: "未来", accept: ["未来"],
    hint: "まだ来ていない時。", exp: "過去→現在→未来。" },
  { id: "kotoba08", category: "kotoba", level: 3, type: "choice",
    q: "「他山の石」の正しい意味はどれ？",
    choices: ["他人の失敗も自分の役に立つ", "山はけずれない", "宝物のこと", "けんかのこと"], answer: "他人の失敗も自分の役に立つ",
    hint: "「石」でもみがく役に立つ。", exp: "「他山の石」＝他人のよくない言動も自分をみがく参考になる。" },

  /* ===== 文章・資料の読み取り ===== */
  { id: "dokkai01", category: "dokkai", level: 1, type: "choice",
    q: "「雨が強くなった。□□、試合は中止になった。」□□に合う言葉は？",
    choices: ["だから", "しかし", "たとえば", "ところが"], answer: "だから",
    hint: "前が原因、後ろが結果になっています。", exp: "原因→結果をつなぐのは「だから」。" },
  { id: "dokkai02", category: "dokkai", level: 1, type: "input",
    q: "「公園に犬がいた。それは茶色だった。」この文の『それ』が指すものは何？", answer: "犬", accept: ["犬", "いぬ"],
    hint: "前の文に出てきたものを指します。", exp: "指示語『それ』は前に出た「犬」を指します。" },
  { id: "dokkai03", category: "dokkai", level: 2, type: "choice",
    q: "「練習はつらい。□□、上達するとうれしい。」□□に合う言葉は？",
    choices: ["でも", "だから", "つまり", "また"], answer: "でも",
    hint: "前後で反対のことを言っています。", exp: "逆のことをつなぐのは「でも（しかし）」。" },
  { id: "dokkai04", category: "dokkai", level: 2, type: "input",
    q: "ある店の来客数は 月100人・火80人・水120人・木90人 でした。最も多かったのは何曜日？", answer: "水", accept: ["水", "水曜", "水曜日"],
    hint: "数字をくらべます。120がいちばん大きい。", exp: "120人の水曜日が最多。資料の読み取りの基本です。" },
  { id: "dokkai05", category: "dokkai", level: 2, type: "input",
    q: "上の店で、月から木の来客数の合計は何人？（月100・火80・水120・木90）", answer: "390", accept: ["390", "390人"],
    hint: "100+80+120+90 を計算します。", exp: "100+80+120+90=390人。" },
  { id: "dokkai06", category: "dokkai", level: 3, type: "choice",
    q: "「努力は必ず実るとは限らない。だが、努力なしに実ることもない。」筆者が最も言いたいことは？",
    choices: ["努力は大切だ", "努力はむだだ", "実りは運で決まる", "努力はつらい"], answer: "努力は大切だ",
    hint: "後半の文に強い思いが出ています。", exp: "「努力なしに実らない」＝努力が大切、という主張です。" },
  { id: "dokkai07", category: "dokkai", level: 2, type: "input",
    q: "あるクラス30人のうち、犬が好きな人は18人。割合は全体の何％？", answer: "60", accept: ["60", "60%", "60％"],
    hint: "18÷30×100 を計算します。", exp: "18÷30=0.6=60％。資料分析でよく使う割合です。" },
  { id: "dokkai08", category: "dokkai", level: 3, type: "choice",
    q: "グラフで『割合』を表すのに最も向いているのはどれ？",
    choices: ["円グラフ", "折れ線グラフ", "ヒストグラム", "数直線"], answer: "円グラフ",
    hint: "全体を100%として分けて見せます。", exp: "割合は円グラフ（や帯グラフ）が向いています。" },

  /* ===== 数の性質・規則性 ===== */
  { id: "kazu01", category: "kazu", level: 1, type: "input",
    q: "2, 4, 6, 8, … と続く数の、10番目の数は？", answer: "20", accept: ["20"],
    hint: "2のだんの数（2×□）です。", exp: "2×10=20。" },
  { id: "kazu02", category: "kazu", level: 2, type: "input",
    q: "1から100までの整数のうち、3の倍数は何個ある？", answer: "33", accept: ["33", "33個"],
    hint: "100÷3 の商を考えます。", exp: "100÷3=33あまり1。3の倍数は33個。" },
  { id: "kazu03", category: "kazu", level: 1, type: "input",
    q: "6と8の最小公倍数はいくつ？", answer: "24", accept: ["24"],
    hint: "6の倍数で8でもわり切れる数。", exp: "6,12,18,24… 8,16,24… 共通で最小は24。" },
  { id: "kazu04", category: "kazu", level: 1, type: "input",
    q: "12と18の最大公約数はいくつ？", answer: "6", accept: ["6"],
    hint: "両方をわり切れる数で最大のもの。", exp: "12=2×2×3, 18=2×3×3。共通は2×3=6。" },
  { id: "kazu05", category: "kazu", level: 2, type: "input",
    q: "1, 3, 6, 10, 15, … と続く数（三角数）の次の数は？", answer: "21", accept: ["21"],
    hint: "たす数が 2,3,4,5,… と1ずつふえます。", exp: "15に6をたして21。" },
  { id: "kazu06", category: "kazu", level: 2, type: "input",
    q: "1から20までの整数の中に、素数は何個ある？", answer: "8", accept: ["8", "8個"],
    hint: "2,3,5,7,11,13,17,19 を数えます。", exp: "素数は2,3,5,7,11,13,17,19の8個。" },
  { id: "kazu07", category: "kazu", level: 2, type: "input",
    q: "1, 2, 4, 8, 16, … と続く数の次の数は？", answer: "32", accept: ["32"],
    hint: "前の数を2倍しています。", exp: "16×2=32。" },
  { id: "kazu08", category: "kazu", level: 3, type: "input",
    q: "100を7でわった余りはいくつ？", answer: "2", accept: ["2"],
    hint: "7×14=98 です。", exp: "7×14=98、100−98=2。" },

  /* ===== 図形 ===== */
  { id: "zukei01", category: "zukei", level: 1, type: "input",
    q: "1辺が6cmの正方形の面積は何cm²？（数だけ答えてOK）", answer: "36", accept: ["36", "36cm2", "36cm²"],
    hint: "1辺×1辺。", exp: "6×6=36cm²。" },
  { id: "zukei02", category: "zukei", level: 1, type: "input",
    q: "たて4cm・よこ7cmの長方形の、まわりの長さは何cm？", answer: "22", accept: ["22", "22cm"],
    hint: "(たて+よこ)×2。", exp: "(4+7)×2=22cm。" },
  { id: "zukei03", category: "zukei", level: 2, type: "input",
    q: "底辺8cm・高さ5cmの三角形の面積は何cm²？", answer: "20", accept: ["20", "20cm2", "20cm²"],
    hint: "底辺×高さ÷2。", exp: "8×5÷2=20cm²。" },
  { id: "zukei04", category: "zukei", level: 1, type: "input",
    q: "三角形の3つの角の大きさをぜんぶたすと何度？", answer: "180", accept: ["180", "180度", "180°"],
    hint: "どんな三角形でも同じ。", exp: "三角形の内角の和は180度。" },
  { id: "zukei05", category: "zukei", level: 2, type: "input",
    q: "1辺3cmの立方体の体積は何cm³？", answer: "27", accept: ["27", "27cm3", "27cm³"],
    hint: "1辺×1辺×1辺。", exp: "3×3×3=27cm³。" },
  { id: "zukei06", category: "zukei", level: 2, type: "input",
    q: "半径10cmの円の面積は何cm²？（円周率は3.14）", answer: "314", accept: ["314", "314cm2", "314cm²"],
    hint: "半径×半径×3.14。", exp: "10×10×3.14=314cm²。" },
  { id: "zukei07", category: "zukei", level: 2, type: "input",
    q: "半径5cmの円の円周は何cm？（円周率は3.14）", answer: "31.4", accept: ["31.4", "31.4cm"],
    hint: "直径×3.14。直径は半径の2倍。", exp: "5×2×3.14=31.4cm。" },
  { id: "zukei08", category: "zukei", level: 3, type: "input",
    q: "正六角形の1つの内角は何度？", answer: "120", accept: ["120", "120度", "120°"],
    hint: "内角の和720度を6でわります。", exp: "正六角形の内角の和は720度。720÷6=120度。" },

  /* ===== 割合・速さ・場合の数 ===== */
  { id: "wariai01", category: "wariai", level: 1, type: "input",
    q: "200円の30％はいくら？", answer: "60", accept: ["60", "60円"],
    hint: "200×0.3。", exp: "200×0.3=60円。" },
  { id: "wariai02", category: "wariai", level: 1, type: "input",
    q: "800円の品物が「5割引き」。代金はいくら？", answer: "400", accept: ["400", "400円"],
    hint: "5割引き＝半分の値段。", exp: "5割引きは半額なので400円。" },
  { id: "wariai03", category: "wariai", level: 1, type: "input",
    q: "時速4kmで3時間歩くと、何km進む？", answer: "12", accept: ["12", "12km"],
    hint: "速さ×時間＝道のり。", exp: "4×3=12km。" },
  { id: "wariai04", category: "wariai", level: 2, type: "input",
    q: "全体200gの食塩水に、食塩が30gとけています。濃度は何％？", answer: "15", accept: ["15", "15%", "15％"],
    hint: "食塩÷食塩水×100。", exp: "30÷200=0.15=15％。" },
  { id: "wariai05", category: "wariai", level: 2, type: "input",
    q: "1, 2, 3 のカードを並べてできる3けたの整数は、全部で何通り？（同じ数字は使わない）", answer: "6", accept: ["6", "6通り"],
    hint: "百の位3通り×十の位2通り×一の位1通り。", exp: "3×2×1=6通り。" },
  { id: "wariai06", category: "wariai", level: 2, type: "input",
    q: "男子と女子の人数の比が 3:2 のクラスに25人。男子は何人？", answer: "15", accept: ["15", "15人"],
    hint: "全体は3+2=5。25÷5=1あたり。", exp: "25÷5=5、男子は5×3=15人。" },
  { id: "wariai07", category: "wariai", level: 2, type: "input",
    q: "10円玉を2回投げます。表と裏の出方は全部で何通り？", answer: "4", accept: ["4", "4通り"],
    hint: "1回で2通り。それが2回。", exp: "2×2=4通り。" },
  { id: "wariai08", category: "wariai", level: 3, type: "input",
    q: "家から学校まで1.2kmを分速60mで歩くと、何分かかる？", answer: "20", accept: ["20", "20分"],
    hint: "1.2km=1200m。1200÷60。", exp: "1200÷60=20分。" },

  /* ===== 理科 ===== */
  { id: "rika01", category: "rika", level: 1, type: "input",
    q: "植物が光合成をするとき、空気中から取り入れる気体は何？", answer: "二酸化炭素", accept: ["二酸化炭素", "二酸化炭素(CO2)", "CO2"],
    hint: "人がはく息に多くふくまれる気体。", exp: "光合成は二酸化炭素を取り入れ、酸素を出します。" },
  { id: "rika02", category: "rika", level: 1, type: "input",
    q: "光合成によって、植物が出す気体は何？", answer: "酸素", accept: ["酸素", "酸素(O2)", "O2"],
    hint: "人が呼吸で取り入れる気体。", exp: "光合成は酸素を出します。" },
  { id: "rika03", category: "rika", level: 1, type: "input",
    q: "水は何℃でこおって氷になる？", answer: "0", accept: ["0", "0度", "0℃", "0°C"],
    hint: "セ氏の基準の温度。", exp: "水は0℃でこおります。" },
  { id: "rika04", category: "rika", level: 1, type: "input",
    q: "こん虫のあしは全部で何本？", answer: "6", accept: ["6", "6本"],
    hint: "クモは8本だけど、こん虫はちがいます。", exp: "こん虫のあしは6本（むね から出ています）。" },
  { id: "rika05", category: "rika", level: 2, type: "choice",
    q: "磁石が引きつける金属はどれ？",
    choices: ["鉄", "アルミニウム", "銅", "金"], answer: "鉄",
    hint: "クリップによく使われる金属。", exp: "磁石につくのは鉄など。アルミ・銅・金はつきません。" },
  { id: "rika06", category: "rika", level: 2, type: "input",
    q: "昼と夜がくり返されるのは、地球が1日に1回まわっているからです。この動きを何という？", answer: "自転", accept: ["自転"],
    hint: "「自分で回る」と書きます。", exp: "地球の自転で昼夜が生まれます（太陽のまわりを回るのは公転）。" },
  { id: "rika07", category: "rika", level: 2, type: "input",
    q: "てこの3つの点は「支点」「力点」と、あと1つは何点？", answer: "作用点", accept: ["作用点"],
    hint: "ものに力がはたらく点。", exp: "支点・力点・作用点。てこのきまりの基本です。" },
  { id: "rika08", category: "rika", level: 3, type: "choice",
    q: "夜空で、太陽の光を反射して光って見えるのはどれ？",
    choices: ["月", "太陽", "北極星", "シリウス"], answer: "月",
    hint: "自分では光らず、満ち欠けします。", exp: "月は自分で光らず、太陽の光を反射しています。星は自分で光ります。" },

  /* ===== 社会 ===== */
  { id: "shakai01", category: "shakai", level: 1, type: "input",
    q: "横浜市があるのは何という都道府県？", answer: "神奈川県", accept: ["神奈川県", "神奈川"],
    hint: "県庁所在地が横浜市です。", exp: "横浜市は神奈川県の県庁所在地です。" },
  { id: "shakai02", category: "shakai", level: 1, type: "input",
    q: "日本でいちばん高い山は何という山？", answer: "富士山", accept: ["富士山", "ふじさん"],
    hint: "標高3776m。", exp: "富士山（3776m）が日本一の高さです。" },
  { id: "shakai03", category: "shakai", level: 2, type: "input",
    q: "日本でいちばん長い川は何という川？", answer: "信濃川", accept: ["信濃川", "しなのがわ"],
    hint: "長野県から新潟県へ流れます。", exp: "信濃川が日本一長い川です。" },
  { id: "shakai04", category: "shakai", level: 2, type: "input",
    q: "国の法律をつくる仕事をする機関は何？", answer: "国会", accept: ["国会"],
    hint: "三権のうち「立法」を担当します。", exp: "法律をつくる（立法）のは国会。内閣＝行政、裁判所＝司法。" },
  { id: "shakai05", category: "shakai", level: 2, type: "input",
    q: "今の日本で、選挙で投票できるのは何歳から？", answer: "18", accept: ["18", "18歳", "18才"],
    hint: "2016年から引き下げられました。", exp: "現在は18歳から投票できます。" },
  { id: "shakai06", category: "shakai", level: 3, type: "choice",
    q: "日本国憲法の三つの原則にふくまれないものはどれ？",
    choices: ["軍国主義", "国民主権", "平和主義", "基本的人権の尊重"], answer: "軍国主義",
    hint: "三原則は「国民主権・平和主義・基本的人権の尊重」。", exp: "三原則に軍国主義は入りません。" },
  { id: "shakai07", category: "shakai", level: 2, type: "choice",
    q: "東京・大阪と並ぶ三大都市の一つで、愛知県にあるのは？",
    choices: ["名古屋", "札幌", "福岡", "仙台"], answer: "名古屋",
    hint: "中部地方の中心都市。", exp: "三大都市圏は東京・大阪・名古屋。" },
  { id: "shakai08", category: "shakai", level: 3, type: "choice",
    q: "2023年ごろ、世界でいちばん人口が多くなった国はどれ？",
    choices: ["インド", "中国", "アメリカ", "日本"], answer: "インド",
    hint: "アジアの国で、中国をぬきました。", exp: "2023年にインドが中国をぬいて世界一の人口になりました。" },

  /* ===== 思考力・パズル ===== */
  { id: "shikou01", category: "shikou", level: 1, type: "input",
    q: "りんご3個とみかん6個が同じねだんです。りんご1個は、みかん何個分？", answer: "2", accept: ["2", "2個"],
    hint: "6÷3を考えます。", exp: "りんご3個＝みかん6個 → りんご1個＝みかん2個分。" },
  { id: "shikou02", category: "shikou", level: 1, type: "choice",
    q: "AはBより背が高く、BはCより背が高い。いちばん背が低いのはだれ？",
    choices: ["C", "A", "B", "わからない"], answer: "C",
    hint: "A>B>C の順にならべます。", exp: "A>B>C なので、いちばん低いのはC。" },
  { id: "shikou03", category: "shikou", level: 2, type: "input",
    q: "今日が月曜日です。10日後は何曜日？", answer: "木曜日", accept: ["木曜日", "木", "木曜"],
    hint: "7日で1週間。10÷7のあまりを考えます。", exp: "10÷7=1あまり3。月曜から3つ進んで木曜日。" },
  { id: "shikou04", category: "shikou", level: 2, type: "input",
    q: "つるとかめが合わせて10匹。あしの数は合計26本。かめは何匹？", answer: "3", accept: ["3", "3匹"],
    hint: "全部つるなら20本。増えた分はかめ。", exp: "全部つる＝20本。26−20=6、6÷2=3匹がかめ。" },
  { id: "shikou05", category: "shikou", level: 2, type: "input",
    q: "まっすぐな100mの道に、はしからはしまで10mおきに木を植えます。木は何本いる？", answer: "11", accept: ["11", "11本"],
    hint: "間の数より木は1本多い（植木算）。", exp: "間は100÷10=10個。両はしに植えるので木は11本。" },
  { id: "shikou06", category: "shikou", level: 3, type: "input",
    q: "2, 3, 5, 8, 12, … と続く数の次の数は？", answer: "17", accept: ["17"],
    hint: "たす数が 1,2,3,4,… とふえています。", exp: "12に5をたして17。" },
  { id: "shikou07", category: "shikou", level: 2, type: "input",
    q: "ある数を3倍して4をたすと19になりました。ある数はいくつ？", answer: "5", accept: ["5"],
    hint: "19から4をひいて3でわります。", exp: "(19−4)÷3=5。" },
  { id: "shikou08", category: "shikou", level: 3, type: "choice",
    q: "「すべてのバラは花である」が正しいとき、必ず正しいと言えるのはどれ？",
    choices: ["バラは花の一種である", "すべての花はバラである", "花でないものはバラ", "バラは花ではない"], answer: "バラは花の一種である",
    hint: "「すべてのバラ＝花」だけど逆は言えません。", exp: "バラ⊂花。逆（すべての花がバラ）は成り立ちません。" },

  /* ===== ことば・漢字（追加） ===== */
  { id: "kotoba09", category: "kotoba", level: 1, type: "input",
    q: "「険しい」の読みをひらがなで答えましょう。", answer: "けわしい", accept: ["けわしい"],
    hint: "山道などが急で歩きにくいようす。", exp: "「険しい（けわしい）」＝傾きが急で危ない・きつい。" },
  { id: "kotoba10", category: "kotoba", level: 1, type: "input",
    q: "「原因」の反対の意味の言葉（対義語）を漢字2字で答えましょう。", answer: "結果", accept: ["結果"],
    hint: "あることが起きた「もと」⇔そのあとに起きた「こと」。", exp: "原因⇔結果。" },
  { id: "kotoba11", category: "kotoba", level: 1, type: "input",
    q: "ことわざ「ちりも積もれば□となる」。□に入る漢字1字は？", answer: "山", accept: ["山"],
    hint: "小さなものも集まれば大きくなる。", exp: "「ちりも積もれば山となる」。" },
  { id: "kotoba12", category: "kotoba", level: 2, type: "input",
    q: "慣用句「□を割ったよう」は、さっぱりした性格のこと。□に入る植物は？", answer: "竹", accept: ["竹"],
    hint: "まっすぐ縦に割れる植物。", exp: "「竹を割ったよう」＝まっすぐで気持ちのよい性格。" },
  { id: "kotoba13", category: "kotoba", level: 2, type: "input",
    q: "「進歩」とほぼ同じ意味の言葉（類義語）を漢字2字で。", answer: "向上", accept: ["向上"],
    hint: "前よりよくなること。", exp: "進歩≒向上。" },
  { id: "kotoba14", category: "kotoba", level: 1, type: "input",
    q: "「易しい」の反対の意味の言葉をひらがなで。", answer: "むずかしい", accept: ["むずかしい", "難しい"],
    hint: "やさしい⇔？", exp: "易しい⇔難しい（むずかしい）。" },
  { id: "kotoba15", category: "kotoba", level: 2, type: "input",
    q: "四字熟語「一挙□得」（一つのことで二つの利益）。□に入る漢字1字は？", answer: "両", accept: ["両"],
    hint: "「両方とも得する」。", exp: "「一挙両得（いっきょりょうとく）」。" },
  { id: "kotoba16", category: "kotoba", level: 2, type: "input",
    q: "慣用句「□耳に水」は、突然のできごとにおどろくこと。□に入る漢字1字は？", answer: "寝", accept: ["寝"],
    hint: "ねているときに水が入ったらびっくり。", exp: "「寝耳に水（ねみみにみず）」。" },
  { id: "kotoba17", category: "kotoba", level: 2, type: "input",
    q: "「街角」の読みをひらがなで答えましょう。", answer: "まちかど", accept: ["まちかど"],
    hint: "町のかどのこと。", exp: "「街角（まちかど）」。" },
  { id: "kotoba18", category: "kotoba", level: 1, type: "choice",
    q: "「弟が　公園で　元気に　遊ぶ」。この文の主語はどれ？",
    choices: ["弟が", "公園で", "元気に", "遊ぶ"], answer: "弟が",
    hint: "「だれが」にあたる言葉。", exp: "主語は「だれが・何が」を表す『弟が』。" },
  { id: "kotoba19", category: "kotoba", level: 3, type: "input",
    q: "四字熟語「温故□新」（古いことを学び新しい知識を得る）。□に入る漢字1字は？", answer: "知", accept: ["知"],
    hint: "「故きを温ねて新しきを□る」。", exp: "「温故知新（おんこちしん）」。" },
  { id: "kotoba20", category: "kotoba", level: 3, type: "choice",
    q: "「絶対」の対義語（反対の意味の言葉）はどれ？",
    choices: ["相対", "反対", "正面", "比例"], answer: "相対",
    hint: "他とのかんけいで決まること。", exp: "絶対⇔相対。" },
  { id: "kotoba21", category: "kotoba", level: 2, type: "input",
    q: "ことわざ「□の耳に念仏」は、いくら言ってもむだなこと。□に入る動物は？", answer: "馬", accept: ["馬", "うま"],
    hint: "「馬」と「ねこ」どちらか。ありがたい話を聞かせても…。", exp: "「馬の耳に念仏」。「ねこに小判」と似た意味。" },
  { id: "kotoba22", category: "kotoba", level: 2, type: "input",
    q: "慣用句「のどから□が出る」は、ほしくてたまらないこと。□に入る体の部分は？", answer: "手", accept: ["手"],
    hint: "ものをつかむ部分。", exp: "「のどから手が出る」。" },
  { id: "kotoba23", category: "kotoba", level: 3, type: "input",
    q: "「往復」の「往」と反対の意味を表す、もう一つの漢字は「復」。では「復」は「行く」「帰る」どちら？", answer: "帰る", accept: ["帰る", "かえる"],
    hint: "往＝行く。復は反対の動き。", exp: "往＝行き、復＝帰り。だから「往復」。" },
  { id: "kotoba24", category: "kotoba", level: 1, type: "input",
    q: "「明るい」の反対の意味の言葉をひらがなで。", answer: "くらい", accept: ["くらい", "暗い"],
    hint: "電気を消した部屋は…？", exp: "明るい⇔暗い（くらい）。" },
  { id: "kotoba25", category: "kotoba", level: 3, type: "choice",
    q: "「百聞は一見にしかず」の意味として正しいものは？",
    choices: ["何度も聞くより一度見るほうがよくわかる", "百回聞けば見なくてよい", "見るより聞くほうが大事", "聞くのも見るのも同じ"], answer: "何度も聞くより一度見るほうがよくわかる",
    hint: "「しかず」＝かなわない。", exp: "「百聞は一見にしかず」＝百回聞くより一度見るほうがよくわかる。" },

  /* ===== 文章・資料の読み取り（追加） ===== */
  { id: "dokkai09", category: "dokkai", level: 1, type: "choice",
    q: "「毎日練習した。□□、本番でうまくいった。」□□に合う言葉は？",
    choices: ["だから", "しかし", "または", "ところで"], answer: "だから",
    hint: "前が理由、後ろがよい結果。", exp: "理由→結果は「だから」。" },
  { id: "dokkai10", category: "dokkai", level: 2, type: "choice",
    q: "「ねむかった。□□、最後までがんばった。」□□に合う言葉は？",
    choices: ["しかし", "だから", "つまり", "そして"], answer: "しかし",
    hint: "前後で逆のことを言っています。", exp: "逆のことをつなぐのは「しかし」。" },
  { id: "dokkai11", category: "dokkai", level: 1, type: "input",
    q: "「つくえの上に本がある。これは姉のものだ。」『これ』が指すものは何？", answer: "本", accept: ["本", "ほん"],
    hint: "前の文に出たものを指します。", exp: "指示語『これ』は「本」を指します。" },
  { id: "dokkai12", category: "dokkai", level: 1, type: "input",
    q: "ある週の最高気温は 月15・火18・水20・木17・金14（℃）でした。最も高かったのは何曜日？", answer: "水", accept: ["水", "水曜", "水曜日"],
    hint: "数字が一番大きい曜日。", exp: "20℃の水曜日が最高です。" },
  { id: "dokkai13", category: "dokkai", level: 2, type: "input",
    q: "上の気温（月15・火18・水20・木17・金14）で、最も高い日と最も低い日の差は何℃？", answer: "6", accept: ["6", "6度", "6℃"],
    hint: "20−14 を計算します。", exp: "20−14＝6℃。資料の読み取りでよく使います。" },
  { id: "dokkai14", category: "dokkai", level: 2, type: "input",
    q: "40人のクラスで、電車通学は10人です。割合は全体の何％？", answer: "25", accept: ["25", "25%", "25％"],
    hint: "10÷40×100。", exp: "10÷40＝0.25＝25％。" },
  { id: "dokkai15", category: "dokkai", level: 2, type: "choice",
    q: "「読書は心の栄養だ。だから本をたくさん読もう。」筆者が言いたいことは？",
    choices: ["本をたくさん読むとよい", "本は栄養になる食べ物だ", "読書はつかれる", "心は栄養がいらない"], answer: "本をたくさん読むとよい",
    hint: "「だから」のあとに主張があります。", exp: "結論は「本をたくさん読もう」。" },
  { id: "dokkai16", category: "dokkai", level: 3, type: "choice",
    q: "時間とともに変わる「気温の変化」を表すのに、最も向いているグラフは？",
    choices: ["折れ線グラフ", "円グラフ", "帯グラフ", "絵グラフ"], answer: "折れ線グラフ",
    hint: "変化のようすは線でつなぐと見やすい。", exp: "変化は折れ線グラフ、割合は円・帯グラフが向いています。" },
  { id: "dokkai17", category: "dokkai", level: 3, type: "input",
    q: "円グラフで、全体の25％にあたる部分の中心角は何度？", answer: "90", accept: ["90", "90度", "90°"],
    hint: "1周360度の25％。", exp: "360×0.25＝90度。" },
  { id: "dokkai18", category: "dokkai", level: 2, type: "choice",
    q: "「努力家の兄は　毎日　練習する。」この文の述語はどれ？",
    choices: ["練習する", "兄は", "毎日", "努力家の"], answer: "練習する",
    hint: "「どうする」にあたる言葉。", exp: "述語は「どうする・どんなだ」を表す『練習する』。" },
  { id: "dokkai19", category: "dokkai", level: 2, type: "input",
    q: "1個120円のりんごを買います。500円では最大何個買える？", answer: "4", accept: ["4", "4個"],
    hint: "120×4＝480、120×5＝600。", exp: "120×4＝480円で4個まで。500円では4個。" },
  { id: "dokkai20", category: "dokkai", level: 2, type: "choice",
    q: "段落の始めで使い、話題を変えるはたらきの言葉はどれ？",
    choices: ["ところで", "だから", "しかし", "つまり"], answer: "ところで",
    hint: "「さて」と同じなかま。", exp: "話題を変えるのは「ところで・さて」。" },
  { id: "dokkai21", category: "dokkai", level: 1, type: "input",
    q: "A組30人・B組28人・C組32人です。3クラスの合計は何人？", answer: "90", accept: ["90", "90人"],
    hint: "30+28+32。", exp: "30+28+32＝90人。" },
  { id: "dokkai22", category: "dokkai", level: 2, type: "input",
    q: "上の3クラス（30・28・32人）の1クラスあたりの平均人数は何人？", answer: "30", accept: ["30", "30人"],
    hint: "合計90÷3。", exp: "90÷3＝30人。" },
  { id: "dokkai23", category: "dokkai", level: 2, type: "choice",
    q: "「つまり」という言葉のはたらきは？",
    choices: ["前の内容のまとめ・言いかえ", "反対のこと", "例をあげる", "話題を変える"], answer: "前の内容のまとめ・言いかえ",
    hint: "前で言ったことを短く言い直すとき。", exp: "「つまり」＝前の内容のまとめ・言いかえ。" },

  /* ===== 数の性質・規則性（追加） ===== */
  { id: "kazu09", category: "kazu", level: 1, type: "input",
    q: "5, 10, 15, … と続く数の、8番目の数は？", answer: "40", accept: ["40"],
    hint: "5×□。", exp: "5×8＝40。" },
  { id: "kazu10", category: "kazu", level: 1, type: "input",
    q: "1から50までの整数のうち、5の倍数は何個ある？", answer: "10", accept: ["10", "10個"],
    hint: "50÷5。", exp: "50÷5＝10個。" },
  { id: "kazu11", category: "kazu", level: 2, type: "input",
    q: "9と12の最小公倍数はいくつ？", answer: "36", accept: ["36"],
    hint: "9の倍数で12でもわり切れる数。", exp: "9,18,27,36… 12,24,36…で最小は36。" },
  { id: "kazu12", category: "kazu", level: 2, type: "input",
    q: "24と36の最大公約数はいくつ？", answer: "12", accept: ["12"],
    hint: "両方をわり切れる最大の数。", exp: "24＝2×2×2×3、36＝2×2×3×3。共通は2×2×3＝12。" },
  { id: "kazu13", category: "kazu", level: 2, type: "input",
    q: "100, 90, 80, … と10ずつ減ります。0になるのは何番目？", answer: "11", accept: ["11", "11番目"],
    hint: "100が1番目。減る回数は10回。", exp: "10回減らすと0。1番目が100なので11番目。" },
  { id: "kazu14", category: "kazu", level: 2, type: "input",
    q: "1+2+3+ … +10 の答えはいくつ？", answer: "55", accept: ["55"],
    hint: "(1+10)×10÷2 で計算できます。", exp: "(1+10)×10÷2＝55。" },
  { id: "kazu15", category: "kazu", level: 2, type: "input",
    q: "1, 4, 9, 16, … と続く数（平方数）の次の数は？", answer: "25", accept: ["25"],
    hint: "1×1, 2×2, 3×3, 4×4 …。", exp: "5×5＝25。" },
  { id: "kazu16", category: "kazu", level: 1, type: "input",
    q: "50を6でわった余りはいくつ？", answer: "2", accept: ["2"],
    hint: "6×8＝48。", exp: "6×8＝48、50−48＝2。" },
  { id: "kazu17", category: "kazu", level: 3, type: "input",
    q: "2けたの整数の中で、いちばん大きい素数はいくつ？", answer: "97", accept: ["97"],
    hint: "99,98,…と下げて、約数が1と自分だけの数をさがします。", exp: "97は素数。98,99は割り切れるので、最大の2けた素数は97。" },
  { id: "kazu18", category: "kazu", level: 1, type: "input",
    q: "偶数を小さい順にならべたとき、8番目の偶数はいくつ？", answer: "16", accept: ["16"],
    hint: "2,4,6,…＝2×□。", exp: "2×8＝16。" },
  { id: "kazu19", category: "kazu", level: 3, type: "input",
    q: "1, 1, 2, 3, 5, 8, … と続く数（となり合う2つの数の和）の次の数は？", answer: "13", accept: ["13"],
    hint: "5+8 を計算します。", exp: "5+8＝13（フィボナッチ数列）。" },
  { id: "kazu20", category: "kazu", level: 3, type: "input",
    q: "60の約数は全部で何個ある？", answer: "12", accept: ["12", "12個"],
    hint: "1,2,3,4,5,6,10,12,15,20,30,60。", exp: "60の約数は12個あります。" },
  { id: "kazu21", category: "kazu", level: 1, type: "choice",
    q: "「3＋5」の答えは、偶数・奇数のどちら？",
    choices: ["偶数", "奇数"], answer: "偶数",
    hint: "8は2でわり切れる？", exp: "3+5＝8。8は偶数（奇数＋奇数＝偶数）。" },
  { id: "kazu22", category: "kazu", level: 3, type: "input",
    q: "1から100までの整数を全部たすといくつ？", answer: "5050", accept: ["5050"],
    hint: "(1+100)×100÷2。", exp: "(1+100)×100÷2＝5050。" },
  { id: "kazu23", category: "kazu", level: 2, type: "input",
    q: "3の倍数でも5の倍数でもある、いちばん小さい整数（0をのぞく）は？", answer: "15", accept: ["15"],
    hint: "3と5の最小公倍数。", exp: "3と5の最小公倍数は15。" },
  { id: "kazu24", category: "kazu", level: 2, type: "input",
    q: "ある数を4でわると商が7、余りが3でした。ある数はいくつ？", answer: "31", accept: ["31"],
    hint: "4×7＋3。", exp: "4×7＝28、28＋3＝31。" },

  /* ===== 図形（追加） ===== */
  { id: "zukei09", category: "zukei", level: 1, type: "input",
    q: "1辺5cmの正方形の、まわりの長さは何cm？", answer: "20", accept: ["20", "20cm"],
    hint: "1辺×4。", exp: "5×4＝20cm。" },
  { id: "zukei10", category: "zukei", level: 1, type: "input",
    q: "たて3cm・よこ8cmの長方形の面積は何cm²？", answer: "24", accept: ["24", "24cm2", "24cm²"],
    hint: "たて×よこ。", exp: "3×8＝24cm²。" },
  { id: "zukei11", category: "zukei", level: 2, type: "input",
    q: "底辺10cm・高さ6cmの平行四辺形の面積は何cm²？", answer: "60", accept: ["60", "60cm2", "60cm²"],
    hint: "底辺×高さ。", exp: "10×6＝60cm²。" },
  { id: "zukei12", category: "zukei", level: 2, type: "input",
    q: "上底4cm・下底6cm・高さ5cmの台形の面積は何cm²？", answer: "25", accept: ["25", "25cm2", "25cm²"],
    hint: "(上底＋下底)×高さ÷2。", exp: "(4+6)×5÷2＝25cm²。" },
  { id: "zukei13", category: "zukei", level: 2, type: "input",
    q: "直径8cmの円の円周は何cm？（円周率は3.14）", answer: "25.12", accept: ["25.12", "25.12cm"],
    hint: "直径×3.14。", exp: "8×3.14＝25.12cm。" },
  { id: "zukei14", category: "zukei", level: 2, type: "input",
    q: "半径3cmの円の面積は何cm²？（円周率は3.14）", answer: "28.26", accept: ["28.26", "28.26cm2", "28.26cm²"],
    hint: "半径×半径×3.14。", exp: "3×3×3.14＝28.26cm²。" },
  { id: "zukei15", category: "zukei", level: 3, type: "input",
    q: "1辺4cmの立方体の表面積は何cm²？", answer: "96", accept: ["96", "96cm2", "96cm²"],
    hint: "1つの面4×4＝16が6面。", exp: "16×6＝96cm²。" },
  { id: "zukei16", category: "zukei", level: 1, type: "input",
    q: "たて2cm・よこ3cm・高さ4cmの直方体の体積は何cm³？", answer: "24", accept: ["24", "24cm3", "24cm³"],
    hint: "たて×よこ×高さ。", exp: "2×3×4＝24cm³。" },
  { id: "zukei17", category: "zukei", level: 1, type: "input",
    q: "正方形の1つの角の大きさは何度？", answer: "90", accept: ["90", "90度", "90°"],
    hint: "直角です。", exp: "正方形の角はすべて90度（直角）。" },
  { id: "zukei18", category: "zukei", level: 1, type: "input",
    q: "四角形の4つの角の大きさをぜんぶたすと何度？", answer: "360", accept: ["360", "360度", "360°"],
    hint: "三角形2つ分（180×2）。", exp: "四角形の内角の和は360度。" },
  { id: "zukei19", category: "zukei", level: 1, type: "input",
    q: "正三角形の1つの角の大きさは何度？", answer: "60", accept: ["60", "60度", "60°"],
    hint: "180度を3等分。", exp: "180÷3＝60度。" },
  { id: "zukei20", category: "zukei", level: 3, type: "input",
    q: "正五角形の5つの角の大きさをぜんぶたすと何度？", answer: "540", accept: ["540", "540度", "540°"],
    hint: "三角形3つ分に分けられます。", exp: "(5−2)×180＝540度。" },
  { id: "zukei21", category: "zukei", level: 2, type: "input",
    q: "1辺6cmの立方体の体積は何cm³？", answer: "216", accept: ["216", "216cm3", "216cm³"],
    hint: "6×6×6。", exp: "6×6×6＝216cm³。" },
  { id: "zukei22", category: "zukei", level: 2, type: "input",
    q: "直角三角形で、直角以外の2つの角をたすと何度？", answer: "90", accept: ["90", "90度", "90°"],
    hint: "三角形の和180度から90度をひく。", exp: "180−90＝90度。" },
  { id: "zukei23", category: "zukei", level: 1, type: "input",
    q: "立方体の面の数はいくつ？", answer: "6", accept: ["6", "6つ", "6面"],
    hint: "サイコロを思いうかべよう。", exp: "立方体の面は6つ。" },
  { id: "zukei24", category: "zukei", level: 2, type: "input",
    q: "立方体の辺の数はいくつ？", answer: "12", accept: ["12", "12本"],
    hint: "上に4本、下に4本、たてに4本。", exp: "立方体の辺は12本。" },
  { id: "zukei25", category: "zukei", level: 2, type: "input",
    q: "立方体の頂点（角）の数はいくつ？", answer: "8", accept: ["8", "8つ"],
    hint: "上に4つ、下に4つ。", exp: "立方体の頂点は8つ。" },
  { id: "zukei26", category: "zukei", level: 3, type: "input",
    q: "半径10cm・中心角90度のおうぎ形の、曲線部分（弧）の長さは何cm？（円周率3.14）", answer: "15.7", accept: ["15.7", "15.7cm"],
    hint: "円周の4分の1。円周は10×2×3.14。", exp: "円周62.8cmの1/4＝15.7cm。" },

  /* ===== 割合・速さ・場合の数（追加） ===== */
  { id: "wariai09", category: "wariai", level: 1, type: "input",
    q: "500円の20％はいくら？", answer: "100", accept: ["100", "100円"],
    hint: "500×0.2。", exp: "500×0.2＝100円。" },
  { id: "wariai10", category: "wariai", level: 2, type: "input",
    q: "300円の品物が「3割引き」。代金はいくら？", answer: "210", accept: ["210", "210円"],
    hint: "3割引き＝7割の値段。300×0.7。", exp: "300×0.7＝210円。" },
  { id: "wariai11", category: "wariai", level: 2, type: "input",
    q: "時速60kmで2時間半進むと、何km進む？", answer: "150", accept: ["150", "150km"],
    hint: "2時間半＝2.5時間。60×2.5。", exp: "60×2.5＝150km。" },
  { id: "wariai12", category: "wariai", level: 2, type: "input",
    q: "120kmの道のりを時速40kmで進むと、何時間かかる？", answer: "3", accept: ["3", "3時間"],
    hint: "道のり÷速さ。", exp: "120÷40＝3時間。" },
  { id: "wariai13", category: "wariai", level: 1, type: "input",
    q: "分速80mで15分歩くと、何m進む？", answer: "1200", accept: ["1200", "1200m"],
    hint: "速さ×時間。", exp: "80×15＝1200m。" },
  { id: "wariai14", category: "wariai", level: 2, type: "input",
    q: "全体300gの食塩水に、食塩が45gとけています。濃度は何％？", answer: "15", accept: ["15", "15%", "15％"],
    hint: "食塩÷食塩水×100。", exp: "45÷300＝0.15＝15％。" },
  { id: "wariai15", category: "wariai", level: 3, type: "input",
    q: "6％の食塩水200gには、食塩が何gとけている？", answer: "12", accept: ["12", "12g"],
    hint: "200×0.06。", exp: "200×0.06＝12g。" },
  { id: "wariai16", category: "wariai", level: 3, type: "input",
    q: "1, 2, 3, 4 のカードから2枚使ってできる2けたの整数は何通り？（同じ数字は使わない）", answer: "12", accept: ["12", "12通り"],
    hint: "十の位4通り×一の位3通り。", exp: "4×3＝12通り。" },
  { id: "wariai17", category: "wariai", level: 3, type: "input",
    q: "赤・白・青の3色から2色を選ぶ選び方は何通り？（順番は考えない）", answer: "3", accept: ["3", "3通り"],
    hint: "（赤白）（赤青）（白青）。", exp: "3通り（組み合わせ）。" },
  { id: "wariai18", category: "wariai", level: 1, type: "input",
    q: "定価1000円の品物を「2割引き」で買うと、いくら？", answer: "800", accept: ["800", "800円"],
    hint: "2割引き＝8割の値段。", exp: "1000×0.8＝800円。" },
  { id: "wariai19", category: "wariai", level: 2, type: "input",
    q: "原価500円の品物に、2割の利益をつけました。定価はいくら？", answer: "600", accept: ["600", "600円"],
    hint: "500×1.2。", exp: "500×1.2＝600円。" },
  { id: "wariai20", category: "wariai", level: 3, type: "input",
    q: "時速36kmは、秒速何m？", answer: "10", accept: ["10", "10m"],
    hint: "36km＝36000m、1時間＝3600秒。", exp: "36000÷3600＝秒速10m。" },
  { id: "wariai21", category: "wariai", level: 1, type: "input",
    q: "1500mの道を分速100mで進むと、何分かかる？", answer: "15", accept: ["15", "15分"],
    hint: "道のり÷速さ。", exp: "1500÷100＝15分。" },
  { id: "wariai22", category: "wariai", level: 2, type: "input",
    q: "あるクラスの人数の2割が8人です。クラス全体は何人？", answer: "40", accept: ["40", "40人"],
    hint: "8が「2割（0.2）」にあたる。8÷0.2。", exp: "8÷0.2＝40人。" },
  { id: "wariai23", category: "wariai", level: 2, type: "input",
    q: "男子と女子の比が 5:3 のクラスで、女子は9人です。男子は何人？", answer: "15", accept: ["15", "15人"],
    hint: "女子3にあたる人数が9。1にあたるのは3人。", exp: "9÷3＝3、男子は3×5＝15人。" },
  { id: "wariai24", category: "wariai", level: 2, type: "input",
    q: "全体を 3:4 の比で分けます。全体が14のとき、小さいほうはいくつ？", answer: "6", accept: ["6"],
    hint: "全体は3+4＝7。14÷7＝1あたり2。", exp: "14÷7＝2、小さいほうは2×3＝6。" },

  /* ===== 理科（追加） ===== */
  { id: "rika09", category: "rika", level: 2, type: "input",
    q: "水が水じょう気（気体）に変わることを何という？", answer: "蒸発", accept: ["蒸発", "じょうはつ"],
    hint: "せんたく物がかわくのも同じはたらき。", exp: "液体の水が気体になることを蒸発といいます。" },
  { id: "rika10", category: "rika", level: 2, type: "input",
    q: "100℃近くで、水の中からもさかんに気体が出てくる現象を何という？", answer: "沸とう", accept: ["沸とう", "ふっとう", "沸騰"],
    hint: "やかんでお湯をわかすと…。", exp: "100℃ふきんで水が激しく気体になることを沸とうといいます。" },
  { id: "rika11", category: "rika", level: 3, type: "choice",
    q: "種が発芽するために、必要ないものはどれ？",
    choices: ["日光", "水", "空気", "適当な温度"], answer: "日光",
    hint: "発芽そのものに光はいりません（育つときには必要）。", exp: "発芽に必要なのは水・空気・適当な温度。日光は発芽には不要です。" },
  { id: "rika12", category: "rika", level: 1, type: "input",
    q: "こん虫のからだは「頭」「むね」と、あと1つは何という部分に分かれている？", answer: "はら", accept: ["はら", "腹"],
    hint: "頭・むね・□の3つ。", exp: "こん虫のからだは頭・むね・はらの3つに分かれます。" },
  { id: "rika13", category: "rika", level: 3, type: "input",
    q: "メダカやヒトのように、背骨のある動物をまとめて何という？", answer: "セキツイ動物", accept: ["セキツイ動物", "せきつい動物", "脊椎動物"],
    hint: "背骨＝せぼね。", exp: "背骨のある動物をセキツイ動物といいます。" },
  { id: "rika14", category: "rika", level: 2, type: "choice",
    q: "次のうち、電気を通すものはどれ？",
    choices: ["鉄くぎ", "ガラス", "木のえんぴつ", "消しゴム"], answer: "鉄くぎ",
    hint: "金属は電気を通します。", exp: "鉄などの金属は電気を通します。" },
  { id: "rika15", category: "rika", level: 1, type: "input",
    q: "太陽は、東・西・南・北のどの方角からのぼる？", answer: "東", accept: ["東", "ひがし"],
    hint: "朝、太陽が出てくる方角。", exp: "太陽は東からのぼり、西にしずみます。" },
  { id: "rika16", category: "rika", level: 3, type: "choice",
    q: "ふりこが1往復する時間は、おもに何で変わる？",
    choices: ["ふりこの長さ", "おもりの重さ", "ふれはば", "ひもの色"], answer: "ふりこの長さ",
    hint: "「ふりこの等時性」。", exp: "1往復の時間はふりこの長さで決まります（重さやふれはばは関係なし）。" },
  { id: "rika17", category: "rika", level: 2, type: "choice",
    q: "1年のうち、昼の長さが最も長くなるのはどの季節？",
    choices: ["夏", "冬", "春", "秋"], answer: "夏",
    hint: "夏至のころ。", exp: "夏（夏至のころ）は昼が最も長くなります。" },
  { id: "rika18", category: "rika", level: 2, type: "input",
    q: "氷・水・水じょう気のうち、「固体」はどれ？", answer: "氷", accept: ["氷", "こおり"],
    hint: "形がしっかりしているもの。", exp: "氷＝固体、水＝液体、水じょう気＝気体。" },
  { id: "rika19", category: "rika", level: 3, type: "input",
    q: "心臓から全身へ送り出される血液が流れる血管を何という？", answer: "動脈", accept: ["動脈", "どうみゃく"],
    hint: "心臓から「出ていく」ほう。", exp: "心臓から出る血管が動脈、心臓へもどる血管が静脈です。" },
  { id: "rika20", category: "rika", level: 3, type: "input",
    q: "食べ物の養分の多くを吸収する、人の体の中の長い管を何という？", answer: "小腸", accept: ["小腸", "しょうちょう"],
    hint: "胃のあと、大腸の前。", exp: "養分の多くは小腸で吸収されます。" },
  { id: "rika21", category: "rika", level: 2, type: "choice",
    q: "月の形（満ち欠け）が、もとの形にもどるまでにかかる日数は約何日？",
    choices: ["約30日", "約7日", "約1日", "約100日"], answer: "約30日",
    hint: "新月→満月→新月で約1か月。", exp: "月の満ち欠けはおよそ30日（約1か月）でひとまわりします。" },
  { id: "rika22", category: "rika", level: 1, type: "input",
    q: "方位じしんの色のついた針（N極）は、どの方角を指す？", answer: "北", accept: ["北", "きた"],
    hint: "北極星のある方角。", exp: "方位じしんのN極は北を指します。" },
  { id: "rika23", category: "rika", level: 3, type: "input",
    q: "豆電球2個を「直列」につなぐと、明るさは1個のときとくらべて明るい・暗いどちら？", answer: "暗い", accept: ["暗い", "くらい", "暗くなる"],
    hint: "電流が流れにくくなります。", exp: "直列につなぐ豆電球を増やすと、1個のときより暗くなります。" },
  { id: "rika24", category: "rika", level: 1, type: "input",
    q: "クモのあしは全部で何本？", answer: "8", accept: ["8", "8本"],
    hint: "こん虫は6本だけど、クモはちがいます。", exp: "クモのあしは8本（クモはこん虫ではありません）。" },

  /* ===== 社会（追加） ===== */
  { id: "shakai09", category: "shakai", level: 1, type: "input",
    q: "日本の首都はどこ？", answer: "東京", accept: ["東京", "東京都", "とうきょう"],
    hint: "国会や政府の中心がある都市。", exp: "日本の首都は東京（東京都）です。" },
  { id: "shakai10", category: "shakai", level: 2, type: "input",
    q: "国の三権のうち、裁判を行うのはどこ？", answer: "裁判所", accept: ["裁判所"],
    hint: "「司法」を担当します。", exp: "裁判を行うのは裁判所（司法）。" },
  { id: "shakai11", category: "shakai", level: 2, type: "input",
    q: "国の三権のうち、法律にもとづいて政治を実際に行う（行政）のはどこ？", answer: "内閣", accept: ["内閣"],
    hint: "総理大臣が中心。", exp: "行政を担当するのは内閣。" },
  { id: "shakai12", category: "shakai", level: 1, type: "input",
    q: "日本でいちばん面積が大きい都道府県は？", answer: "北海道", accept: ["北海道", "ほっかいどう"],
    hint: "日本の北のはし。", exp: "面積が最大の都道府県は北海道。" },
  { id: "shakai13", category: "shakai", level: 3, type: "input",
    q: "日本でいちばん面積が小さい都道府県は？", answer: "香川県", accept: ["香川県", "香川", "かがわ"],
    hint: "四国にある県。うどんで有名。", exp: "面積が最小の都道府県は香川県。" },
  { id: "shakai14", category: "shakai", level: 2, type: "input",
    q: "世界でいちばん面積が大きい国は？", answer: "ロシア", accept: ["ロシア", "ロシア連邦"],
    hint: "ユーラシア大陸の北に大きく広がる国。", exp: "世界一面積が大きい国はロシア。" },
  { id: "shakai15", category: "shakai", level: 2, type: "input",
    q: "日本でいちばん大きい湖は何という湖？", answer: "琵琶湖", accept: ["琵琶湖", "びわ湖", "びわこ"],
    hint: "滋賀県にあります。", exp: "日本最大の湖は琵琶湖（滋賀県）。" },
  { id: "shakai16", category: "shakai", level: 2, type: "choice",
    q: "自動車工業がさかんで、豊田市がある都道府県は？",
    choices: ["愛知県", "大阪府", "福岡県", "北海道"], answer: "愛知県",
    hint: "中部地方、名古屋市がある県。", exp: "自動車工業の中心地の一つが愛知県（豊田市）。" },
  { id: "shakai17", category: "shakai", level: 1, type: "input",
    q: "都道府県は全部でいくつある？", answer: "47", accept: ["47", "47個"],
    hint: "1都1道2府43県。", exp: "日本の都道府県は47。" },
  { id: "shakai18", category: "shakai", level: 3, type: "input",
    q: "国会・内閣・裁判所に権力を3つに分けるしくみを何という？", answer: "三権分立", accept: ["三権分立", "さんけんぶんりつ"],
    hint: "1か所に力が集まりすぎないように。", exp: "権力を立法・行政・司法に分けるしくみが三権分立。" },
  { id: "shakai19", category: "shakai", level: 2, type: "input",
    q: "6月ごろに雨やくもりの日が続く時期を何という？", answer: "梅雨", accept: ["梅雨", "つゆ", "ばいう"],
    hint: "あじさいの花がきれいなころ。", exp: "6月ごろの長雨の時期を梅雨（つゆ）といいます。" },
  { id: "shakai20", category: "shakai", level: 2, type: "input",
    q: "外国へ品物を売ることを何という？", answer: "輸出", accept: ["輸出", "ゆしゅつ"],
    hint: "「出す」ほう。", exp: "外国へ売るのが輸出、買うのが輸入。" },
  { id: "shakai21", category: "shakai", level: 1, type: "input",
    q: "外国から品物を買い入れることを何という？", answer: "輸入", accept: ["輸入", "ゆにゅう"],
    hint: "「入れる」ほう。", exp: "外国から買うのが輸入。" },
  { id: "shakai22", category: "shakai", level: 3, type: "choice",
    q: "中部地方にある、高くけわしい3つの山脈（飛驒・木曽・赤石）をまとめて何という？",
    choices: ["日本アルプス", "ヒマラヤ山脈", "ロッキー山脈", "アンデス山脈"], answer: "日本アルプス",
    hint: "ヨーロッパの山脈の名前がついています。", exp: "飛驒・木曽・赤石山脈をまとめて日本アルプスといいます。" },
  { id: "shakai23", category: "shakai", level: 2, type: "input",
    q: "国民の願いを実現するため、税金などを使って国や地方が行う仕事を何という？（漢字2字）", answer: "政治", accept: ["政治", "せいじ"],
    hint: "国会や役所が行う仕事。", exp: "国や地方公共団体が行う仕事を政治といいます。" },
  { id: "shakai24", category: "shakai", level: 1, type: "input",
    q: "横浜市は、何という地方にある？（関東・近畿などの地方名）", answer: "関東", accept: ["関東", "関東地方", "かんとう"],
    hint: "東京都と同じ地方。", exp: "横浜市（神奈川県）は関東地方にあります。" },

  /* ===== 思考力・パズル（追加） ===== */
  { id: "shikou09", category: "shikou", level: 1, type: "input",
    q: "みかん2個とりんご1個が同じねだんです。みかん8個は、りんご何個分？", answer: "4", accept: ["4", "4個"],
    hint: "みかん2個＝りんご1個。8÷2。", exp: "みかん8個＝りんご4個分。" },
  { id: "shikou10", category: "shikou", level: 1, type: "choice",
    q: "AはBより大きく、CはAより大きい。いちばん大きいのはだれ？",
    choices: ["C", "A", "B", "わからない"], answer: "C",
    hint: "C>A>B の順。", exp: "C>A>B なので、いちばん大きいのはC。" },
  { id: "shikou11", category: "shikou", level: 1, type: "input",
    q: "今日が金曜日です。5日後は何曜日？", answer: "水曜日", accept: ["水曜日", "水", "水曜"],
    hint: "金→土→日→月→火→水。", exp: "金曜から5日進むと水曜日。" },
  { id: "shikou12", category: "shikou", level: 2, type: "input",
    q: "つるとかめが合わせて8匹。あしの数は合計22本。かめは何匹？", answer: "3", accept: ["3", "3匹"],
    hint: "全部つるなら16本。増えた分はかめ。", exp: "全部つる＝16本。22−16＝6、6÷2＝3匹がかめ。" },
  { id: "shikou13", category: "shikou", level: 2, type: "input",
    q: "まっすぐな50mの道に、はしからはしまで5mおきに木を植えます。木は何本いる？", answer: "11", accept: ["11", "11本"],
    hint: "間の数は50÷5＝10。木は1本多い。", exp: "間10個＋両はしで木は11本。" },
  { id: "shikou14", category: "shikou", level: 2, type: "input",
    q: "1, 4, 9, 16, 25, … と続く数の6番目は？", answer: "36", accept: ["36"],
    hint: "1×1, 2×2, … 6×6。", exp: "6×6＝36。" },
  { id: "shikou15", category: "shikou", level: 2, type: "input",
    q: "ある数から7をひいて3倍したら27になりました。ある数はいくつ？", answer: "16", accept: ["16"],
    hint: "27÷3＝9、それに7をたす。", exp: "27÷3＝9、9＋7＝16。" },
  { id: "shikou16", category: "shikou", level: 1, type: "input",
    q: "3, 6, 12, 24, … と続く数の次は？", answer: "48", accept: ["48"],
    hint: "前の数を2倍。", exp: "24×2＝48。" },
  { id: "shikou17", category: "shikou", level: 3, type: "input",
    q: "100, 95, 85, 70, … と続きます（引く数が5,10,15…とふえる）。次の数は？", answer: "50", accept: ["50"],
    hint: "次は20をひきます。", exp: "70−20＝50。" },
  { id: "shikou18", category: "shikou", level: 2, type: "input",
    q: "りんご3個で240円です。同じねだんなら、5個では何円？", answer: "400", accept: ["400", "400円"],
    hint: "1個のねだんを先に求める。", exp: "240÷3＝80円、80×5＝400円。" },
  { id: "shikou19", category: "shikou", level: 2, type: "input",
    q: "兄は弟より3才年上で、2人の年れいの合計は15才です。弟は何才？", answer: "6", accept: ["6", "6才", "6歳"],
    hint: "(15−3)÷2。", exp: "(15−3)÷2＝6才が弟。" },
  { id: "shikou20", category: "shikou", level: 2, type: "input",
    q: "1周1200mの池のまわりを、分速60mで1周します。何分かかる？", answer: "20", accept: ["20", "20分"],
    hint: "1200÷60。", exp: "1200÷60＝20分。" },
  { id: "shikou21", category: "shikou", level: 3, type: "input",
    q: "時計が「3時ちょうど」のとき、長い針と短い針がつくる小さいほうの角度は何度？", answer: "90", accept: ["90", "90度", "90°"],
    hint: "文字ばん1つ分は30度。3つ分。", exp: "数字1つ分＝30度。3時は3つ分はなれて30×3＝90度。" },
  { id: "shikou22", category: "shikou", level: 2, type: "input",
    q: "ある仕事を1人ですると6日かかります。同じ速さの3人ですると何日？", answer: "2", accept: ["2", "2日"],
    hint: "人数が3倍になると日数は3分の1。", exp: "6÷3＝2日。" },
  { id: "shikou23", category: "shikou", level: 3, type: "input",
    q: "2, 5, 10, 17, 26, … と続きます（差が3,5,7,9…）。次の数は？", answer: "37", accept: ["37"],
    hint: "次は11をたします。", exp: "26＋11＝37。" },
  { id: "shikou24", category: "shikou", level: 3, type: "choice",
    q: "「すべての犬は動物である」が正しいとき、必ず正しいと言えるのはどれ？",
    choices: ["犬は動物の一種である", "すべての動物は犬である", "動物でないものは犬", "犬は動物ではない"], answer: "犬は動物の一種である",
    hint: "「すべての犬＝動物」。逆は言えません。", exp: "犬⊂動物。逆（すべての動物が犬）は成り立ちません。" },
];

// グローバルからアクセスできるようにする
window.CATEGORIES = CATEGORIES;
window.QUESTIONS = QUESTIONS;
